apiVersion: v1
kind: Pod
metadata:
  name: writer
spec:
  containers:
  - name: writer
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        echo "Hello from $(hostname) at $(date)" > /data/hello.txt
        echo "Wrote file; sleeping so you can exec into this pod..."
        sleep 3600
    volumeMounts:
      - name: data
        mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc
