version: "3.9"

services:
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
