services:
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "/run/secrets/redis_password"]
    secrets:
      - redis_password

  app:
    build: .
    depends_on:
      - redis
    secrets:
      - redis_password

secrets:
  redis_password:
    file: ./secrets/redis_password.txt
