apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-app
  labels:
    app: config-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-secret-app
  template:
    metadata:
      labels:
        app: config-secret-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MODE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
