apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-flask
  template:
    metadata:
      labels:
        app: capstone-flask
    spec:
      containers:
      - name: flask
        image: islahuddin26/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
