apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: local-pvc
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "while true; do echo $(date) >> /data/log.txt; sleep 5; done" ]
    volumeMounts:
    - mountPath: /data
      name: storage-volume
